### ISSUE TITLE
neo4j_at_scale_airline_dataset

### ISSUE THREAD

**Issue by jexp** [bytefish/bytefish.de#10]
Thanks a lot for your article.

- LOAD CSV is fully transactional
- if possible you should create a constraint/index for the id-lookup fields of each entity
- the non-transactional bulk-importer is used with `neo4j-import` or `neo4j-admin import` for offline initial loading. It can sustain about 1M records / s .
- neo4j doesn't really work well without an SSD (esp. in terms of write performance)

- thanks a lot for the feedback on `unwind` and the `foreach` trick for optional relationships. you are right, both could be better.

For your query, could you try this variant and see if it makes a difference.

```
MATCH (:Reason {description:'Weather'})
MATCH (a:Airport)
WITH r, a, size( (a)<-[:ORIGIN]-() ) as total
MATCH (a)<-[:ORIGIN]-(f:Flight)-[:DELAYED_BY]->(r)
WITH a, total, COUNT(f) AS num
RETURN a.abbr + ' - ' + a.name AS Airport, ((1.0 * num) / total) * 100 AS Percent
ORDER BY Percent DESC
LIMIT 10

```

Please note that your query is a full graph query which is more analytical. Cypher was originally built for local-transactional queries but is getting there.
As any database Neo4j benefits from being able to keep as much data as possible in RAM, so a configuration setup that utilizes that makes sense.
And Neo4j Enterprise (which has a free developer edition) has a faster query engine.

**Comment by bytefish** [comment]
Thanks for the explanation! I will check the query and let you know.

**Comment by bytefish** [comment]
@jexp I won't be able to evaluate it before the weekend. Before I start: Do you have any hints, which configuration settings in the ``neo4j.conf`` I should adjust? I will of course also follow the Neo4j documentation on Performance settings.

**Comment by jexp** [comment]
Don't worry :) it's holiday weekend after all.

Basically look at the store size and adjust the page-cache setting to fit that, e.g. 6G and then use e.g. 8G for heap. See below.

Definitely, check out Neo4j Desktop with Neo4j Enterprise 3.3.5


```
# Java Heap Size: by default the Java heap size is dynamically
# calculated based on available system resources.
# Uncomment these lines to set specific initial and maximum
# heap size.
dbms.memory.heap.initial_size=8G
dbms.memory.heap.max_size=8G

# The amount of memory to use for mapping the store files, in bytes (or
# kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g').
# If Neo4j is running on a dedicated server, then it is generally recommended
# to leave about 2-4 gigabytes for the operating system, give the JVM enough
# heap to hold all your transaction state and query context, and then leave the
# rest for the page cache.
# The default page cache memory assumes the machine is dedicated to running
# Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size.
dbms.memory.pagecache.size=6G
```

**Comment by bytefish** [comment]
The database has a size of ``2.36`` GB. I have used your proposed configuration, which should fit the database. Then I ran your query on a cold run and with a second run.

## First Run ##

An interesting thing happens here. If I start the Neo4j database and ran the query you provided, it takes ``250`` seconds to finish. The disk spins at 99% during the query. Maybe I have misconfigured the database?

![image](https://user-images.githubusercontent.com/239373/39876372-460ce8e0-5473-11e8-9165-635562f5c257.png)

## Second Run ##

Subsequent runs on the database apparently have the Neo4j Database cached in RAM. I see no disk activity and the queries finish consistently in ``13.5`` seconds. 

![image](https://user-images.githubusercontent.com/239373/39876574-dc302ba2-5473-11e8-9b74-bdd9324279fd.png)

## Query Plan ##

![image](https://user-images.githubusercontent.com/239373/39875482-0e128e74-5471-11e8-9ee5-f4d85596c01f.png)
