### ISSUE TITLE
Update for restsharp_custom_json_serializer.md

### ISSUE THREAD

**Issue by quetzalcoatl** [bytefish/bytefish.de#11]
I'm sorry for not sending a PR, I'm in the middle of other work and it's hard to switch.
Regarding: https://github.com/bytefish/bytefish.de/blob/master/blog/restsharp_custom_json_serializer.md

RestSharp changed a bit, I updated your code a little, you can find the snippets in 
https://github.com/adamfisher/RestSharp.Serializers.Newtonsoft.Json/issues/8#issuecomment-388804040

There's also a tiny issue of `NewtonsoftJsonSerializer.Default` being not defined on your `NewtonsoftJsonSerializer` class, but it shouldn't be a problem for anyone except total novices.

**Comment by quetzalcoatl** [comment]
Nevermind, I didn't notice that `IJsonSerializer` was defined by you few paragraphs earlier. I thought it was an obsoleted interface from RestSharp.

**Comment by bytefish** [comment]
@quetzalcoatl I think I will change the post to your version and directly implement multiple interfaces. Defining an ``IJsonSerializer`` interface has confused quite a lot people, you are not the first one.

**Comment by bytefish** [comment]
@quetzalcoatl I have removed the obsolete ``IJsonSerializer`` interface. Thanks again for letting me know.
