### ISSUE TITLE
'Method not found: 'Void TinyCsvParser.CsvParserOptions..ctor(Boolean, Char)

### ISSUE THREAD

**Issue by RakshaChoudhary** [bytefish/bytefish.de#14]
Hi,

I am trying to learn elastic search using .net. I downloaded your code and trying to run this. But this is giving below error when its trying to call below code 

private static IEnumerable<CsvStationType> GetStations(string fileName)
        {
            return Parsers.StationParser
                .ReadFromFile(fileName, Encoding.ASCII)
                .Where(x => x.IsValid)
                .Select(x => x.Result)
                .AsEnumerable();                
        }:

Error is as below 
'Method not found: 'Void TinyCsvParser.CsvParserOptions..ctor(Boolean, Char)

Please help me in fixing this issue.

**Comment by bytefish** [comment]
The article was based on TinyCsvParser version < 2.0. Please install TinyCsvParser 1.6.0 and it should work:

```
Install-Package TinyCsvParser -Version 1.6.0
```
