### ISSUE TITLE
Confusion regarding radius and sampling points in real life problems.

### ISSUE THREAD

**Issue by dipayan6ghosh** [bytefish/bytefish.de#15]
I went through several LBP's. There are radius and sampling points. If we draw a circle with radius then the points intersecting the pixels are the pixels that are to be taken for while forming the binary code.  I cannot figure out few of them in the image.
<Radius| Sampling Points|>
1 | 4 |  
1 | 8 |  
1 | 16 |  
2 | 4 |  
2 | 8 |  
2 | 16 |  

![test](https://user-images.githubusercontent.com/33153253/42064219-066023f4-7b53-11e8-8628-324dcf5c03ed.jpg)

**Comment by bytefish** [comment]
I think it might help you to look into the implementation: https://github.com/bytefish/facerec/blob/master/py/facerec/lbp.py#L78. You can see, that the floor and ceiling is calculated for each sampling point and the value is calculated using a linear interpolation. Does this help you a little?

**Comment by bytefish** [comment]
Here are also some more explanations with varying radius and sampling points for LBP: https://towardsdatascience.com/face-recognition-how-lbph-works.

**Comment by dipayan6ghosh** [comment]
Though it is in python, I will try to understand it. thanks :)
