### ISSUE TITLE
APNS example

### ISSUE THREAD

**Issue by slthomason** [bytefish/bytefish.de#16]
Hi there,

Any chance you could show a working example of APNS push notification.  Particularly of interest would be an MDM specific command:

https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/3-MDM_Protocol/MDM_Protocol.html#//apple_ref/doc/uid/TP40017387-CH3-SW3

Thanks!

**Comment by bytefish** [comment]
Maybe you could use Google Translate to read this: https://teamsmiley.github.io/2018/07/16/fcm-ios. Let me know if it helps.

**Comment by slthomason** [comment]
Wow!  Thanks for the quick response.  I will definitely work thru this.

So I see that you are using Notification.  What is the difference between
Notification and the APNS objects in the Message type?

**Comment by bytefish** [comment]
Nono, this is not my page. 😃 I just saw it once and thought it might help you. 🤔 Honestly I don't know about APNS and Push Messages with iOS. I just implemented the protocol. A Notification works for both Android and Apple iOS, while it is also quite limited. The AndroidConfig and APNS will allow you more options for the target platform.

**Comment by bytefish** [comment]
Please let me know, if there are problems with APNS messages through FcmSharp. I am sorry I am not much of a help here. 🙏
