### ISSUE TITLE
Bad gateways on the Samples - ERROR 502

### ISSUE THREAD

**Issue by AlvaroN1997** [bytefish/bytefish.de#17]
Trying to download and make use of your beautiful projects, but i cant take the other .py to run the the program :(

**Comment by AlvaroN1997** [comment]
In your page, in the category "Detect a face with OpenCV" the samples links doesn't work, it show the error 502
`samples/python2/video.py`
`samples/python2/coomon.py`

**Comment by bytefish** [comment]
You should find the samples of the latest OpenCV Version here: https://github.com/opencv/opencv. I will update the links in the post.

**Comment by bytefish** [comment]
I have removed links and added a Note, that the post related to OpenCV 2.x. Thanks for filing the issue!
