### ISSUE TITLE
MarkdownEmojiExtension Error

### ISSUE THREAD

**Issue by neon1ks** [bytefish/bytefish.de#21]
The site is not generated. 

The following error occurs: "TypeError: cannot convert dictionary update sequence element #0 to a sequence".

I use pelican 4.0.1 and Markdown 3.0.1.

**Comment by bytefish** [comment]
I generate the pages with the latest Pelican 3.x. I haven't tried Pelican 4. There might be breaking changes. I will check it, thanks for raising the issue.

**Comment by bytefish** [comment]
I just tried it with a fresh Pelican 4.0.1 virtualenv.

I started by installing the MarkdownEmojiExtension:

```
(pelican4) D:\github\MarkdownEmojiExtension>python setup.py install
```

And then install Pelican 4.0.1:

```
(pelican4) D:\github\bytefish.de>pelican --version
4.0.1
```

Then I have built the pages with the following command:

```
(pelican4) D:\github\bytefish.de>pelican -s settings\settings_dev.py .
WARNING: %s usage in TAG_FEED_RSS is deprecated, use {slug} instead.
Done: Processed 97 articles, 0 drafts, 6 pages, 0 hidden pages and 0 draft pages in 14.85 seconds.
```

Hope it helps. 👍

**Comment by neon1ks** [comment]
You used python 2 or python 3 ?

**Comment by bytefish** [comment]
I think it is Python3, but I can check it later.

**Comment by bytefish** [comment]
@neon1ks I was wrong, it is Python 2:

```
(pelican4) D:\>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
```

**Comment by neon1ks** [comment]
I have Ubuntu 16.04 64 bit and Python 3.5.

**Comment by bytefish** [comment]
I have updated virtualenv and run Python3:

```
(pelican4) D:\github\bytefish.de>python --version
Python 3.5.2
```

But I can still build the pages without any problems:

```
(pelican4) D:\github\bytefish.de>pelican -s settings\settings_dev.py .
Done: Processed 97 articles, 0 drafts, 6 pages, 0 hidden pages and 0 draft pages in 13.74 seconds.
```

**Comment by neon1ks** [comment]
I'm sorry. I found a mistake:

```diff
 MARKDOWN = {
+  'extensions' : [EmojiExtension.create_from_json('/home/maksim/neon1ks.ru/resources/emojis.json')],
   'extension_configs': {
-#    'extensions' : [EmojiExtension.create_from_json('/home/maksim/neon1ks.ru/resources/emojis.json')],
     'markdown.extensions.codehilite': {'css_class': 'highlight'},
     'markdown.extensions.extra': {},
     'markdown.extensions.meta': {},
```

Thank you very much for the extension. I will write an article about the extension in Russian.

**Comment by bytefish** [comment]
@neon1ks Great, that you found the error! 😎 Happy 2️⃣0️⃣1️⃣9️⃣.
