### ISSUE TITLE
Displaying the Connectionid required

### ISSUE THREAD

**Issue by samdoss** [bytefish/bytefish.de#24]
![image](https://user-images.githubusercontent.com/3086475/53926864-0640b500-40ab-11e9-9f1f-4e1fd10972aa.png)

**Comment by samdoss** [comment]
What are the steps I need to follow? Please help me.

**Comment by bytefish** [comment]
This article was written a year ago. What SignalR NuGet package and TypeScript client you are using? When I wrote it, SignalR was a Release Candidate 1.0 and not final. You can try installing the same versions I used.

You basically start the Server first, then the Client Application and then you can open the browser to see the updates.
