### ISSUE TITLE
Getting Error : The registration token is not a valid FCM registration token

### ISSUE THREAD

**Issue by mcamauryasatish** [bytefish/bytefish.de#25]
I am using right device token : "3215575407206244294-2953275565396661154-3"
{
  "error": {
    "code": 400,
    "message": "The registration token is not a valid FCM registration token",
    "errors": [
      {
        "message": "The registration token is not a valid FCM registration token",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by bytefish** [comment]
The FcmSharp and FcmJava repositories are archived and I am not actively supporting it anymore. Please use the official Firebase SDKs for .NET or Java (whichever you are using).
