### ISSUE TITLE
java.lang.NoClassDefFoundError: de/bytefish/jtinycsvparser/tokenizer/ITokenizer

### ISSUE THREAD

**Issue by imrandurani** [bytefish/bytefish.de#27]
Hi, Sorry I am new to Apache Flink, I have tried to setup the project though as it.

When I run *flink run -c csv.sorting.PrepareWeatherData* on an already Maven compiled jar file, it throws a **NoClassDefFoundError** error. The jtinycsvparser dependancy is already added to POM with version 1.2. 

Also can you please guide a little how to run this project? I mean which file to execute? Again sorry for my stupid question, since I am new to Flink. 

Please take a look at the attached screenshot. 

Thanks in advance. 

![Selection_011](https://user-images.githubusercontent.com/43948731/58745597-5ef2d480-8485-11e9-9f7f-e164e001ec68.png)

**Comment by bytefish** [comment]
Flink Version? Java Version?

**Comment by imrandurani** [comment]
Flink Version 1.6.2, Java Version 1.8

**Comment by bytefish** [comment]
It's a simple Java app, no need to run it with "flink run". 😎 Does it change something , if you just run it with ``java``?

**Comment by imrandurani** [comment]
I have tried to run app via Intellij Idea, but nothing, since it requires some specific file to be executed. 
Please note! I am using Linux 16.04 LTS. How to run directly with Java?

**Comment by bytefish** [comment]
How did you create the project? You basically import the POM and have IntelliJ to build the project. Then IntelliJ resolves th libraries. Finally you do a Right Click on the Java File and select Run.

**Comment by bytefish** [comment]
You start by importing the Project like this:

![image](https://user-images.githubusercontent.com/239373/58751076-1f82b300-849a-11e9-8d0f-8744a72df40e.png)

Then click through the Wizard with Next, Next. Finish. IntelliJ will then begin to resolve the Maven dependencies for you and create the project.

Next for the sample of the blog post you have to sort the input data, which is done by running the following application:

![image](https://user-images.githubusercontent.com/239373/58751106-74262e00-849a-11e9-9f94-f6752bcfc0ab.png)

Be sure to adjust the Filenames in the program:

![image](https://user-images.githubusercontent.com/239373/58751119-ac2d7100-849a-11e9-98f2-7de6b5540cf8.png)

Now you can run the Streaming Data Example like this:

![image](https://user-images.githubusercontent.com/239373/58751138-e434b400-849a-11e9-86c7-cb1a647d8703.png)

I have just tried it and it still works. 👍
