### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by alfredherr** [bytefish/bytefish.de#30]
Thank you for posting the article on separating [EF Core from the domain](https://bytefish.de/blog/modular_ef_core/). It's excellent!

Do you plan to update it to EF 3? I'm kind of new to EF and am still unsure if there are any changes in v. 3 which may change, hopefully simplify the approach even more.

**Comment by bytefish** [comment]
@alfredherr Thanks for the kind words! I didn't have time to look into the most recent Entity Framework changes yet. 😓 I think there is a new API surface, that will indeed make some "homegrown" parts of my solution obsolete! I will definitely look into it, but I cannot say when. If you want, we can also collaborate on this.

**Comment by bytefish** [comment]
I am currently very short on time with our two 👶👶. I have added a TODO flag, but I cannot promise if I can look into it, this year. 😳

**Comment by bytefish** [comment]
@alfredherr I referenced a wrong commit here. Sorry for this. I will close this issue, because right now I just don't have the time to update the code to EF 3.0. I hope you are not too disappointed. 🙏

**Comment by alfredherr** [comment]
Oh no problem at all bud!. Thank you for taking it into consideration in the first place
