### ISSUE TITLE
Detecting extra columns after last mapped column

### ISSUE THREAD

**Issue by Ronald-rijsdorp** [bytefish/bytefish.de#32]
Thanks for this great library. Works fine, only issue i have is that it seems that the library does not detect that a line contains extra columns after the last mapped column. Missing columns are detected extra columns are not detected.

**Comment by bytefish** [comment]
@Ronald-rijsdorp Thanks for your message! Are you referring to TinyCsvParser? If so I am currently in the process of identifying features for a 3.0: https://github.com/bytefish/TinyCsvParser/issues/58. You can describe your feature request there and probably describe what the "API of your dreams" would look like and what should happen with unmapped columns.

**Comment by Ronald-rijsdorp** [comment]
Hi Philipp,

Thanks for your quick reply. Yes i was referring to the TinyCsvParser. Will
add my feature request.

Met vriendelijke groet,

Ronald Rijsdorp
Software Engineer


m: +31 (0)6-54697478  |  ronaldrijsdorp@itzos.nl <gilpeeters@itzos.nl>  |
www.itzos.nl

**Comment by Ronald-rijsdorp** [comment]
Hi Philipp,

Any idea what the planned release date is for TinyCsvParser version 3.0.

Met vriendelijke groet,

Ronald Rijsdorp
Software Engineer


m: +31 (0)6-54697478  |  ronaldrijsdorp@itzos.nl <gilpeeters@itzos.nl>  |
www.itzos.nl

**Comment by bytefish** [comment]
Hi Ronald, not really. I have just become a father of two girls, so I am somewhat limited in my freetime besides the job. Maybe it is a better path for you to look at CsvHelper? It covers way more edge cases I wasn't able to cover, due to lack of time and libraries design decisions.

**Comment by Ronald-rijsdorp** [comment]
Hi Philipp,

Congrats with the birth of your 2 girls. I can imagine that you are very
busy with your two girls and spending time with your children is far more
valuable than sitting behind a computer staring at code (although
programming can be fun). Will take a look at CsvHelper.

Met vriendelijke groet,

Ronald Rijsdorp
Software Engineer


m: +31 (0)6-54697478  |  ronaldrijsdorp@itzos.nl <gilpeeters@itzos.nl>  |
www.itzos.nl

**Comment by bytefish** [comment]
Hi Ronald, thanks for your kind words and understanding!
