### ISSUE TITLE
Location of Octave code for Discriminant Analysis

### ISSUE THREAD

**Issue by K7LRK** [bytefish/bytefish.de#33]
I would like to use your Octave code for Discriminant Analysis (10/2011) 

-- I'm kind of new to GitHub so probably I just spaced it -- but -- I'm not finding the code.

Can you tell me where to look?

Clark

**Comment by bytefish** [comment]
@K7LRK No worries. The Octave project is here: https://github.com/bytefish/facerec/tree/master/m.

**Comment by K7LRK** [comment]
Great — Thanks
