### ISSUE TITLE
Thank you for the excellent article. Unfortunately, it did not work for me.

### ISSUE THREAD

**Issue by vpateleeoc** [bytefish/bytefish.de#35]
I followed the article and created my table. However, I got this error while inserting a row in the audit table. Instead of inserting an integer in column "rev", it tried to insert a hashmap.

**"ClassCastException: java.util.HashMap cannot be cast to java.lang.Integer"**

Some additional information from the log:
Hibernate: select nextval ('hibernate_sequence')
Hibernate: insert into ims_audit.revinfo (revtstmp, rev) values (?, ?)
2020-02-21 08:31:34 TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [1] as [BIGINT] - [1582291894650]
2020-02-21 08:31:34 TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [2] as [INTEGER] - [71]
Hibernate: insert into ims_audit.private_charging_party (REVTYPE, REVEND, address_line1, address_line2, cell_number, city, country, county, date_of_birth, email_address, extension, fax_number, first_name, home_phone, is_hispanic, language_code, last_name, mediation_reply, middle_initial, name_prefix, name_suffix, national_origin, organization_name, other_language, position_statement_release_dte, position_statement_request, position_statement_request_dte, race, sex, sign_language_need, state, work_phone, zip_code, charging_party_id, REV) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

**The problem is here:**
**_binding parameter [27] as [INTEGER] - [{REV=PrepaRevisionEntity [getRevisionDate()=Fri Feb 21 08:31:34 EST 2020, hashCode()=1743932516, toString()=BaseRevisionEntity [revisionNumber=71, revisionTimestamp=1582291894650], getClass()=class gov.eeoc.prepa.ws.modern.entity.common.SampleRevisionEntity], respondentId=66}]_**

2020-02-21 08:31:34 ERROR org.hibernate.AssertionFailure - HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.Integer

**Comment by bytefish** [comment]
It says unable to bind parameter [27] as INTEGER. Does it probably refer to a column you try to insert?

![image](https://user-images.githubusercontent.com/239373/75061434-023abc80-54e1-11ea-82c1-b02efb56b516.png)

**Comment by bytefish** [comment]
I saw this Stackoverflow Post, which I assume is by you. There you have also posted the Annotated Entity. I see there is a property named "originalId". Could you try to rename the property to something else, maybe this causes a problem:

* https://github.com/hibernate/hibernate-orm/search?q=originalId&unscoped_q=originalId

I also added a commented to your post on GitHub:

* https://stackoverflow.com/questions/60326913/hibernate-envers-throws-classcastexception-hashmap-cannot-cast-to-integer

**Comment by bytefish** [comment]
According to:

* https://stackoverflow.com/questions/60326913/hibernate-envers-throws-classcastexception-hashmap-cannot-cast-to-integer

The problem was indeed the property named "originalId".
