### ISSUE TITLE
Spring Boot Multitenancy guide - Error with AbstractRoutingDataSource

### ISSUE THREAD

**Issue by konstantinosdiam** [bytefish/bytefish.de#39]
Hello, I followed the following guide https://bytefish.de/blog/spring_boot_multitenancy/ regarding Spring Boot Multitenancy, but I have some issues with the AbstractRoutingDataSource.

My project compiles without any problem, but everytime I am trying to run the project, then have the following problem.

The problem is that it throws an IllegalStateException("Cannot determine target DataSource for lookup key [" + lookupKey + "]"). (You can see the output log in the attached file).
I tried to DEBUG the project, so when it accesses TenantAwareRoutingSource, then it goes to AbstractRoutingDataSource determineTargetDataSource() method. But inside this method, it throws the above exception.

I have attached the output log (including the error).
[error.txt](https://github.com/bytefish/bytefish.de/files/4558280/error.txt)

Bear in mind that my project is a web service. So, I am using SoapUI to make the requests. That means that I cannot use the HTTP interceptor to retrieve the tenant name from the header, but I already pass the tenant name as a parameter in the WSDL.

I am looking forward to your reply.

Thank you
Konstantinos

**Comment by bytefish** [comment]
The DataSource is determined by the Tenant, that is written into the ``ThreadLocal`` in the ``ThreadLocalStorage`` class. Based on this Tenant Name the DataSource is determined. Could you see in the Debugging, if the Tenant Name is set correctly? If it is not where in your Request Pipeline do you set the Tenant Name? Feel free to write a mail, so we don't have to discuss everything here.

**Comment by bytefish** [comment]
And if I look into the Log, I see that the Tenant Name is somehow null:

```
Cannot determine target DataSource for lookup key [null]
```

What I suggest is to set the Tenant Name for a small Test directly in the SOAP Endpoints method, like:

```java
ThreadLocalStorage.setTenantName("TenantOne");
```

Then the Tenant Name should be correctly resolved in the code using the Data Sources.

**Comment by konstantinosdiam** [comment]
Thank you very much for your reply.

My email is kostantinosdiam@outlook.com.

In the meantime, I will hardcode the ThreadLocalStorage.setTenantName("TenantOne"); like you said.
