### ISSUE TITLE
Query on spring abstractroutingdatasource advantage

### ISSUE THREAD

**Issue by technok** [bytefish/bytefish.de#40]
I am trying to understand more on the abstractRouting that spring offers.
1. Wouldn’t a hashmap suffice the purpose of the lookup. I am trying to understand what advantage does the thread bound context brings in abstract routing ?
2. What advantages does the AbstractRoutingDatasource brings in specific, since the same could be achieved using a simple if-else logic to determine the target from the hashmap?

**Comment by bytefish** [comment]
Surely it is not the only way to achieve multitenancy in an application, it's just that it is nicely integrated to Spring Boot and requires minimal plumbing to integrate it. 

What would your implementation with HashMap look like?

**Comment by bytefish** [comment]
I don't know what's being asked exactely. I am sure there are alternative approaches. But the ``AbstractRoutingDataSource`` is probably the easiest way when using the Spring Framework and it integrates well into it.
