### ISSUE TITLE
Add a flow diagram

### ISSUE THREAD

**Issue by Adrian1110** [bytefish/bytefish.de#42]
Hi,

First I would like to thank you for your time and for this article.
I would like to suggest to add a flow diagram for this project for a better understanding. What happens from the request until the real response.

I didn't compliantly understand the flow but if you want I can try to create one and later to adjust the diagram based on your suggestions. 

I think this could help. :)

PS: Nice work!

**Comment by bytefish** [comment]
@Adrian1110 Which article do you mean?

**Comment by Adrian1110** [comment]
This one from here : https://bytefish.de/blog/spring_boot_multitenancy/

**Comment by bytefish** [comment]
If it's about the Multi-Tenancy: I think it would be sufficient to have a detailed description of the flow at the beginning of the post. Like 

1. Request flows in with Header X
2. Header X is extracted and Tenant Name is written to a ThreadLocal
3. DataSource is selected by using an AbstractRoutingDataSource and the Tenant in the ThreadLocal. This is done by the AbstractRoutingDataSource being a Data Source Implementation and overriding the ``getConnection`` method.
4. The JPA EntityManager uses this Tenant-aware DataSource to resolve the Database Connections and thus makes queries to the specific Tenant DB.
5. Response is sent
6. ThreadLocal is reset to prevent leaking Tenants

What do you think, would this help?

**Comment by Adrian1110** [comment]
Yes I think this will help as a short intro for the application flow.

**Comment by bytefish** [comment]
I will add it!

**Comment by felipefrocha** [comment]
Thanks man! It will be great to have this reference!

**Comment by bytefish** [comment]
I totally forgot about this issue. 👴 I have added the Request flow to the article, so it is easier to follow the article. 

Please reopen or make a Pull Request if there is something unclear or missing.
