### ISSUE TITLE
NEST not working

### ISSUE THREAD

**Issue by NtsikaMngoma** [bytefish/bytefish.de#43]
Hello, I am getting this error. Please enlighten me on what I am missing: 
"Invalid NEST response built from a unsuccessful () low level call on POST: /documents/_search?typed_keys=true\r\n# Audit trail of this API call:\r\n - [1] BadRequest: Node: http://localhost:9200/ Took: 00:00:00.0879444\r\n - [2] CancellationRequested: Took...

**Comment by bytefish** [comment]
Hard to tell, you might have a better chance asking the NEST folks at:

* https://github.com/elastic/elasticsearch-net

Please create an issue in their issue tracker, I cannot see what's the problem.
