### ISSUE TITLE
Adding null in AuditQueryResultUtil

### ISSUE THREAD

**Issue by VishwasGarg23** [bytefish/bytefish.de#44]
In AuditQueryResultUtil.java :

If type.isInstance is false, then what? Do we add null value entity in the AuditQueryResult? Can you explain this decision?

This is in regard to the item[1], item[2] instance check.

**Comment by bytefish** [comment]
I don't know what's asked or what's the problem. Yes the result will be null, if the types doesn't match.

**Comment by VishwasGarg23** [comment]
I'm sorry. Just want to understand one thing.
Why not raise an exception. Because adding null doesn't make any sense, right?

Please correct or educate me.

**Comment by bytefish** [comment]
Actually back then I had no idea. If you think an exception is better at that point, feel free to use it. There is no specific reason for setting it to null.
