### ISSUE TITLE
How the tenant can be changed on runtime

### ISSUE THREAD

**Issue by hmartinez3661** [bytefish/bytefish.de#45]
Hello, I followed the guide https://bytefish.de/blog/spring_boot_multitenancy/ regarding Spring Boot Multitenancy, It is what I was loking for to solve an issue in my first spring boot proyect.

My project compiles without any problem, but everytime I am trying to run the project I get java.lang.NullPointerException. I don't know what is going on, but let's suppose every thind works fine, could you tell me how the tenant can be changed on runtime???

Regards,
Hugo

**Comment by bytefish** [comment]
There is a great article by @beskow on how to do this:

* https://callistaenterprise.se/blogg/teknik/2020/10/03/multi-tenancy-with-spring-boot-part3/

It shows how to manage tenants and adding them at runtime.
