### ISSUE TITLE
Can't write CLR type System.DateTime to database type timestamp with time zone

### ISSUE THREAD

**Issue by Prad4github** [bytefish/bytefish.de#46]
I am using NodaTime in my application and while using  copyHelper.SaveAll(connection, entitys); I am getting "Can't write CLR type System.DateTime to database type timestamp with time zone" as error.
In my application what i have done :
1.  services.AddDbContextPool<xxxx>((options) =>
            {
                options.UseNpgsql(connectionStrings, optionsBuilder =>
                {
                    optionsBuilder.UseNodaTime();
                });
            });

2. var copyHelper = new PostgreSQLCopyHelper<T>("xx", "yyyyy")
.Map("columnname", x => x.columnname, NpgsqlDbType.TimestampTZ)
copyHelper.SaveAll(connection, entitys);

Hence, I am getting issue "Can't write CLR type System.DateTime to database type timestamp with time zone".
is NodaTime supported into this package.

**Comment by bytefish** [comment]
Yes, it is supported by now. Please try the ``PostgreSQLCopyHelper.NodaTime`` package, which is now available on NuGet.
