### ISSUE TITLE
AbstractMap used by PersonMap in SqlMapper blog entry doesn't match java.util.AbstractMap

### ISSUE THREAD

**Issue by zelmak** [bytefish/bytefish.de#47]
In https://github.com/bytefish/bytefish.de/blob/master/blog/sqlmapper.md PersonMap extends AbstractMap<Person>. The built in java.util.AbstractMap doesn't work with the code you provided. For one, it expects two generic parameters and you're only providing one. Second, there is no constructor with two strings in AbstractMap. Lastly, there is no method named "map."

Are you referencing a different AbstractMap from a different framework?

**Comment by bytefish** [comment]
I am referring to this: 

* https://github.com/bytefish/SqlMapper/blob/master/SqlMapper/src/main/de/bytefish/sqlmapper/AbstractMap.java

I should have chosen a better name, than AbstractMap.

**Comment by zelmak** [comment]
Is that repo hidden from public? I get a 404 from that link.

**Comment by bytefish** [comment]
Oh, it was! I have set visibility to public again.

**Comment by zelmak** [comment]
Aha! Thanks! Consider your oath fulfilled. 👍

**Comment by bytefish** [comment]
🙏

**Comment by zelmak** [comment]
Ack! You moved my cheese! Ah, well... ;)
