### ISSUE TITLE
Update async multi-tenant example

### ISSUE THREAD

**Issue by jeunetoujour** [bytefish/bytefish.de#48]
Have you thought about updating spring_boot_multitenancy_async.md to use Spring Boot's Webflux instead of having to code it old school style with your own threads and Async everywhere?

**Comment by bytefish** [comment]
Sounds good, but I haven’t been doing Java or Spring Boot in a while. I didn’t even hear about Webflux yet. 🙈 I think the biggest change would be propagating the current tenant through the entire call stack. It’s probably not a good idea to use a ThreadLocal for passing the data around. 

This could help:

* https://nickolasfisher.com/blog/How-to-Forward-Request-Headers-to-Downstream-Services-in-Spring-Boot-Webflux

But as far as I can see, this way of propagating state has already been deprecated:

* https://github.com/reactor/reactor-core/issues/2572

I guess the most foolproof way is to pass the Tenant information as a parameter to all downstream services. Might pollute the APIs a bit, but at least that doesn’t involve any magic.

**Comment by bytefish** [comment]
This is also a discussion on how to implement it Multi-Tenancy in Webflux:

* https://github.com/spring-projects/spring-data-r2dbc/issues/98

**Comment by bytefish** [comment]
I gave it a try this morning and implemented it with WebFlux:

* https://github.com/bytefish/SpringBootMultiTenancy_WebFlux

I am not 100% sure about best practices with Mono / Flux in Spring Boot.

Let me know, what you think.
