### ISSUE TITLE
How to addnew datasource without  @Scheduled 

### ISSUE THREAD

**Issue by quoctv0109** [bytefish/bytefish.de#52]
How to I can add new data source without  @Scheduled. Such as when I call a request, the method insertOrUpdateDataSources() will called.

**Comment by bytefish** [comment]
I think you can find some ideas over at: 

* https://callistaenterprise.se/blogg/teknik/2020/09/20/multi-tenancy-with-spring-boot-part2/

The series covers a lot of scenarios in depth. 

I cannot provide an implementation.
