### ISSUE TITLE
dotnet quit unexpectedly on macOS

### ISSUE THREAD

**Issue by chauhannneha** [bytefish/bytefish.de#6]
Hi, 

Can anyone please help me with this issue which I am getting while running dotnet on my mac?
I came across a good number of solutions, which I tried implementing but I think I am just getting confused with so many options to resolve this issue.

Details are as followed:

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by bytefish** [comment]
Did you try to post a question to the Issue Tracker of the ``dotnet/cli`` project? You can find it at https://github.com/dotnet/cli/. 

Maybe they can help you out. 🤔
