### ISSUE TITLE
CORS Filter in JerseyExample project does not catch all Preflight requests

### ISSUE THREAD

**Issue by szauner** [bytefish/bytefish.de#7]
Hi,
I tried to setup a project that has to use CORS and used your Tutorial at https://bytefish.de/blog/cors_with_jersey/ to do so. Unfortunately I cannot get it wo word. And I also do not really understand how it should.
I get that the base resource should handle all the Preflight-requests. But how dies that work if you use @Path with methods in a Resource.
So for example you have a Jersey application at "/api" and a resource at "/service". So of course a preflight request to "/api/service" will be caught by the BaseResource implementation. But how should that also work for a path like "/api/service/add" or "/api/service/multiply"?
The reason why I'm asking is that for me it doesn't. Browsers keep complaining about failed Preflight requests. It works if I just define a new endpoint at for example "/api/service/add" using the OPTIONS-method. Then the Preflight request will be successfull for that endpoint. So do you just assume that there are no path-parts below the resource path defined at class level except for parameters? Or am I missing something?

**Comment by szauner** [comment]
By the way, could you make the example project public or point me to where I can find it? I was not successful when looking for it at GitHub.

**Comment by szauner** [comment]
Back to my original question am I right or missing someting?

I was wondering if it was a possibility to process preflight requests in the filter, too. Currently you're explicitely excepting the preflight request from the processing in the CrossOriginRepsonseFilter and relocating the work to the BaseResource. Which in my opinion leads to the fact that you can not use the @Path annotation in its full extent for methods like described above.
But if you process the Preflight requests also in the filter you could just alter the status code to 200 if a resource has not been found or if OPTIONS is not an allowed method. I'm not sure if that works or if Jersey will just not use the filter in the error case. What do you think about that idea?

**Comment by szauner** [comment]
Well actually I just noticed that Jersey creates a standard OPTIONS handler for every existing path. So why make the difference for preflight requests and others in the filter at all? Could we not just set the CORS filter in general or maybe if that interferes with the Annotation-Logic in a separate second filter?

**Comment by bytefish** [comment]
You are correct I think, no you are not missing something. When looking at the code now, I guess a CORS Filter would be totally sufficient and the Base Resource is obsolete (and probably leads to problems with Paths like you mentioned). 

Thanks for the hints, I will refactor it and update the blog article accordingly.

**Comment by szauner** [comment]
Cool, thanks for the answer!

**Comment by szauner** [comment]
Just wanted to let you know, that there is a shortcomming of my suggestion, that I just encountered:
The annotation @CrossOrigin won't work because the name binding will not be transferred to the autogenerated OPTIONS handlers.
However I wonder If you would have to add the @CrossOrigin-annotation to your BaseResource. Actually I did not try your solution with the annotation, I just left that out.

**Comment by bytefish** [comment]
@szauner You were totally right. I accidentally attributed all my endpoints with the ``@CrossOrigin`` attribute, so the requests to the specific endpoint always had the CORS headers. The catch-all endpoint was never hit, which again highlights the importance of Integration Tests. Sadly I do not have time to fix this in a way an implementation would fully cover the CORS specification. And it is not useful to throw out half-baked solutions. 

So I have deleted the blog post to not spread wrong information. 

Thanks again for notifying me!

I hope you are not too disappointed with me, but I simply have no time.

**Comment by szauner** [comment]
Hi, no no I am not disappointed at all. I thank you very much for the clarification we reached ;-)
